server:
  port: 8888
spring:
  application:
    name: spring-cloud-ribbon
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
 # -- Configure for Ribbon:
  
ping-server:
  ribbon:
    eureka:
      enabled: false # Disable Default Ping
    listOfServers: localhost:8000,localhost:8001,localhost:8002,localhost:8003
    ServerListRefreshInterval: 15000
    
